Repository leapdao/solEVM-enforcer, pull requests merged in 2019-05, with the labels that each got.

#98 Remove EVMLogs, take hydrated state hash into test
  contracts/EVMConstants.sol
  contracts/EVMLogs.slb
  contracts/EVMRuntime.sol
  contracts/EthereumRuntime.sol
  contracts/HydratedRuntime.sol
  contracts/Merkelizer.slb
  contracts/Verifier.sol
  test/contracts/ethereumRuntime.js
  test/contracts/onChain.test.js
  test/contracts/verifier.js
  test/fixtures/dispute.js
  test/fixtures/runtime.js
  test/utils/dispute.js
  test/utils/stepper.js
  tools/executionPoker/ExecutionPoker.js
  utils/DisputeMock.js
  utils/EthereumRuntimeAdapter.js
  utils/Merkelizer.js
  utils/OffchainStepper.js
Labels: in progress

#101 add modexp precompile
  .travis.yml
  contracts/EVMRuntime.sol
  test/fixtures/runtime.js
  test/utils/stepper.js
Labels: billable, size-XS

#104 Support for EC_{ADD,MUL} precompile contracts
  contracts/EVMConstants.sol
  contracts/EVMRuntime.sol
  test/fixtures/runtime.js
Labels: billable, size-XS

#105 Support EC_PAIRING precompile
  contracts/EVMRuntime.sol
  test/fixtures/runtime.js
Labels: billable, size-xxs

#102 Update dispute respond and timeout logic
  contracts/Enforcer.sol
  contracts/Verifier.sol
  contracts/mocks/VerifierMock.sol
  test/contracts/enforcer.js
  test/contracts/verifier.js
  test/helpers/assertRevert.js
  test/helpers/utils.js
  tools/executionPoker/bin.js
Labels: in progress
